[package]
name = "awsc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "awsc"
path = "src/main.rs"

[dependencies]
aws-cli-model = { workspace = true }
aws-cli-protocol = { workspace = true }
aws-cli-runtime = { workspace = true }
aws-cli-output = { workspace = true }
serde_json = { workspace = true }
regex = "1"
