//! The golden corpus: the reference CLI's command surface, extracted by
//! `scripts/extract-reference-surface.py`.
//!
//! This is ground truth. When our surface and the corpus disagree, the corpus is right
//! by definition — it is what the Python CLI actually accepts today.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
pub struct Corpus {
    #[serde(default)]
    pub awscli_version: String,
    #[serde(default)]
    pub services: BTreeMap<String, Service>,
    #[serde(default)]
    pub global_arguments: Vec<String>,
    /// Services the extractor could not load. Recorded rather than fatal, so one broken
    /// model doesn't cost us the other 400.
    #[serde(default)]
    pub errors: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
pub struct Service {
    #[serde(default)]
    pub operations: BTreeMap<String, Operation>,
}

#[derive(Debug, Deserialize)]
pub struct Operation {
    #[serde(default)]
    pub arguments: Vec<String>,
    /// Positional operands, recorded separately by the extractor for 16 operations
    /// (`logs tail`'s `group_name`, `s3 cp`'s `paths`, ...). The surface diff treats
    /// flags and positionals as one argument set — see [`Operation::all_arguments`].
    #[serde(default)]
    pub positional_arguments: Vec<String>,
}

impl Operation {
    /// Flags and positionals merged, as the diff compares them.
    pub fn all_arguments(&self) -> impl Iterator<Item = &String> {
        self.arguments.iter().chain(self.positional_arguments.iter())
    }
}

impl Corpus {
    /// Conventional location, relative to the workspace root.
    pub fn default_path() -> PathBuf {
        workspace_root().join("tests/golden/reference-surface.json")
    }

    /// Returns `Ok(None)` when the corpus has not been generated yet, so tests can skip
    /// cleanly on a fresh clone rather than failing for an unrelated reason.
    pub fn load_default() -> Result<Option<Self>, String> {
        let path = Self::default_path();
        if !path.exists() {
            return Ok(None);
        }
        Self::load(&path).map(Some)
    }

    pub fn load(path: &Path) -> Result<Self, String> {
        let bytes = std::fs::read(path).map_err(|e| format!("reading {}: {e}", path.display()))?;
        serde_json::from_slice(&bytes).map_err(|e| format!("parsing {}: {e}", path.display()))
    }

    pub fn total_operations(&self) -> usize {
        self.services.values().map(|s| s.operations.len()).sum()
    }

    pub fn total_arguments(&self) -> usize {
        self.services
            .values()
            .flat_map(|s| s.operations.values())
            .map(|o| o.all_arguments().count())
            .sum()
    }
}

pub fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

pub fn models_dir() -> PathBuf {
    workspace_root().join("models")
}

/// The botocore paginator overlay, generated by `scripts/extract-paginators.py` and
/// checked in. Unlike `models/`, its absence is an error once models are present —
/// surface derivation is measurably wrong without it.
pub fn paginators_path() -> PathBuf {
    workspace_root().join("data/paginators.json")
}

/// The pure-data customization tables (arg renames, removals, aliases), generated by
/// `scripts/extract-customizations.py` and checked in. Same policy as the paginator
/// overlay: required once models are present.
pub fn customizations_path() -> PathBuf {
    workspace_root().join("data/customizations.json")
}

/// Per-service surface patches, custom commands and the botocore waiter catalogue,
/// generated by `scripts/extract-custom-surface.py`. Same policy again.
pub fn custom_surface_path() -> PathBuf {
    workspace_root().join("data/custom-surface.json")
}
