#!/usr/bin/env python3
"""Generate the sdkId -> `aws <command>` service-name mapping.

Why this exists
---------------
The CLI's service command name is botocore's *data directory name*
(``awscli/botocore/data/<name>/``). That name is not carried in the Smithy models the
Rust port loads, and no rule recovers it:

    endpointPrefix                   308/430  (71.6%)
    serviceId lower, spaces removed  273/430  (63.5%)
    serviceId lower, spaces->hyphen  378/430  (87.9%)

Using endpointPrefix would rename ``aws cloudwatch`` to ``aws monitoring`` and get 122
services wrong. So the mapping is extracted from the reference install rather than
derived.

The join key is ``serviceId``, which is unique across all 430 services and is the same
value Smithy publishes as ``aws.api#service.sdkId`` ("CloudWatch Logs", "S3", ...).

Renames are picked up for free: we read the CLI name from the driver's command table key
and the botocore directory from the command's own ``service_name``, so customizations
like ``s3`` -> ``s3api`` are captured empirically instead of hardcoded.

Usage:  scripts/extract-service-names.py [--output PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REFERENCE_SITE_PACKAGES = (
    "/opt/homebrew/Cellar/awscli/2.36.22/libexec/lib/python3.14/site-packages"
)
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "data" / "service-names.json"


def load_reference():
    """Import awscli from the reference install, isolated from local AWS config."""
    if not os.path.isdir(REFERENCE_SITE_PACKAGES):
        sys.exit(
            f"reference install not found at {REFERENCE_SITE_PACKAGES}\n"
            "install awscli v2, or edit REFERENCE_SITE_PACKAGES."
        )
    sys.path.insert(0, REFERENCE_SITE_PACKAGES)

    # Keep local profiles, plugins and env from perturbing the surface.
    os.environ["AWS_CONFIG_FILE"] = os.devnull
    os.environ["AWS_SHARED_CREDENTIALS_FILE"] = os.devnull
    os.environ.pop("AWS_PROFILE", None)
    os.environ.pop("AWS_DEFAULT_PROFILE", None)

    from awscli.clidriver import create_clidriver  # noqa: E402

    return create_clidriver()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    driver = load_reference()
    session = driver.session
    loader = session.get_component("data_loader")

    command_table = driver._get_command_table()

    mapping: dict[str, str] = {}
    unresolved: list[str] = []
    collisions: list[str] = []

    for cli_name, command in sorted(command_table.items()):
        # ServiceCommand keeps the botocore directory name in the private `_service_name`
        # while the command-table key is the (possibly renamed) CLI name -- that split is
        # what makes renames like `s3` -> `s3api` fall out for free. Custom top-level
        # commands (`configure`, `history`, the high-level `s3`, ...) are LazyCommands
        # with no botocore model and no sdkId, so they cannot be keyed this way and are
        # reported separately.
        botocore_name = getattr(command, "_service_name", None)
        if not botocore_name:
            unresolved.append(cli_name)
            continue

        try:
            model = loader.load_service_model(botocore_name, "service-2")
        except Exception as exc:  # noqa: BLE001 - report, don't abort the other 400
            unresolved.append(f"{cli_name} ({exc.__class__.__name__})")
            continue

        service_id = model.get("metadata", {}).get("serviceId")
        if not service_id:
            unresolved.append(f"{cli_name} (no serviceId)")
            continue

        if service_id in mapping and mapping[service_id] != cli_name:
            collisions.append(f"{service_id}: {mapping[service_id]} vs {cli_name}")
            continue
        mapping[service_id] = cli_name

    payload = {
        "_comment": (
            "Generated by scripts/extract-service-names.py. Maps Smithy "
            "aws.api#service.sdkId to the `aws <command>` name. Do not hand-edit."
        ),
        "awscli_version": driver.session.user_agent_version,
        "services": dict(sorted(mapping.items())),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(f"mapped     {len(mapping)} services", file=sys.stderr)
    print(f"unmapped   {len(unresolved)} (no botocore model)", file=sys.stderr)
    for name in unresolved:
        print(f"             {name}", file=sys.stderr)
    if collisions:
        print(f"COLLISIONS {len(collisions)}", file=sys.stderr)
        for c in collisions:
            print(f"             {c}", file=sys.stderr)
    print(f"wrote      {args.output}", file=sys.stderr)
    return 1 if collisions else 0


if __name__ == "__main__":
    raise SystemExit(main())
