#!/usr/bin/env python3
"""Vendor botocore's waiter definitions, keyed by CLI name.

Why this exists
---------------
`aws <service> wait <name>` polls an operation until an acceptor matches. The
Smithy models this port derives from *do* carry waiters
(``smithy.waiters#waitable``), but they are not the same waiters: Smithy models
some the reference CLI does not have, and — the part that matters — Smithy has
**no attempt limit**. It specifies exponential backoff between ``minDelay`` and
``maxDelay`` and waits indefinitely, where botocore polls ``maxAttempts`` times
at a fixed ``delay`` and then fails. Deriving from Smithy would give a command
that looks right and never times out, so the definitions come from botocore.

``data/custom-surface.json`` already records *which* waiters the reference
exposes, under CLI names. This adds what is needed to actually run them: the
operation, the delay, the attempt cap and the acceptors.

Mapping botocore's data directory to the CLI service name goes through
``metadata.serviceId`` in each ``service-2.json``, which is the same value
Smithy publishes as ``sdkId`` and which ``data/service-names.json`` already
joins on. No guessing from directory names, which disagree
(``codedeploy`` -> ``deploy``, ``config`` -> ``configservice``, ``s3`` ->
``s3api``).

Usage:  scripts/extract-waiters.py --botocore PATH/TO/botocore [--output PATH]

PATH/TO/botocore is a checkout or an unpacked sdist -- the directory holding
``data/``. Nothing is downloaded here; pass a tree you already have.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

# botocore's own transformation, reproduced for waiter and operation names.
_XFORM_FIRST = re.compile(r'(.)([A-Z][a-z]+)')
_XFORM_SECOND = re.compile(r'([a-z0-9])([A-Z])')


def xform_name(name: str, sep: str = '-') -> str:
    if sep in name:
        return name.lower()
    s1 = _XFORM_FIRST.sub(rf'\1{sep}\2', name)
    return _XFORM_SECOND.sub(rf'\1{sep}\2', s1).lower()


def latest_version_dir(service_dir: pathlib.Path) -> pathlib.Path | None:
    versions = sorted(
        (p for p in service_dir.iterdir() if p.is_dir()), reverse=True
    )
    for version in versions:
        if (version / "waiters-2.json").is_file():
            return version
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = pathlib.Path(__file__).resolve().parent.parent
    parser.add_argument("--botocore", type=pathlib.Path, required=True)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=root / "crates" / "awsc-model" / "data" / "waiters.json",
    )
    args = parser.parse_args()

    data_dir = args.botocore / "data"
    if not data_dir.is_dir():
        print(f"{data_dir} is not a directory", file=sys.stderr)
        return 1

    names = json.loads(
        (root / "crates" / "awsc-model" / "data" / "service-names.json").read_text()
    )["services"]

    waiters: dict[str, dict[str, dict]] = {}
    skipped: list[str] = []
    for service_dir in sorted(data_dir.iterdir()):
        if not service_dir.is_dir():
            continue
        version = latest_version_dir(service_dir)
        if version is None:
            continue
        model = json.loads((version / "service-2.json").read_text())
        service_id = model.get("metadata", {}).get("serviceId")
        cli_name = names.get(service_id)
        if cli_name is None:
            skipped.append(f"{service_dir.name} (serviceId {service_id!r})")
            continue

        definitions = json.loads((version / "waiters-2.json").read_text())
        for waiter_name, config in definitions.get("waiters", {}).items():
            waiters.setdefault(cli_name, {})[xform_name(waiter_name)] = {
                "operation": xform_name(config["operation"]),
                "delay": config["delay"],
                "maxAttempts": config["maxAttempts"],
                "acceptors": config["acceptors"],
            }

    payload = {
        "_comment": (
            "Generated by scripts/extract-waiters.py from botocore's "
            "waiters-2.json. Keys are CLI service names; each waiter carries the "
            "CLI-spelled operation it polls, botocore's delay and maxAttempts, "
            "and the acceptors verbatim. Smithy's own waiter traits are NOT used: "
            "they specify no attempt limit, so a waiter derived from them would "
            "never time out."
        ),
        "waiters": waiters,
    }
    args.output.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n")
    total = sum(len(v) for v in waiters.values())
    print(f"wrote {total} waiters across {len(waiters)} services to {args.output}")
    if skipped:
        print(f"skipped {len(skipped)} services with no CLI name:", file=sys.stderr)
        for entry in skipped[:10]:
            print(f"  {entry}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
