#!/usr/bin/env python3
"""Vendor per-service protocol metadata that the Smithy models do not carry.

Currently one field: `targetPrefix`, the value awsJson protocols put in the
`X-Amz-Target` header as `{targetPrefix}.{OperationName}`.

The Smithy models omit `targetPrefix` from their `aws.protocols#awsJson1_x` traits
entirely. The service *shape name* matches botocore's value for 149 of 152 awsJson
services -- but not all: `cloudtrail`, `codeconnections` and `codestar-connections` use a
fully-qualified prefix (e.g. `com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101`).
Deriving it would send those three services a wrong `X-Amz-Target` and fail every call,
so the value is extracted rather than guessed.

Keyed by `serviceId` (== Smithy `aws.api#service.sdkId`), matching the other overlays.

Usage:  scripts/extract-protocol-metadata.py [--output PATH]
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys
from pathlib import Path

REFERENCE_SITE_PACKAGES = (
    "/opt/homebrew/Cellar/awscli/2.36.22/libexec/lib/python3.14/site-packages"
)
DATA_GLOB = f"{REFERENCE_SITE_PACKAGES}/awscli/botocore/data/*/*/service-2.json"
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "data" / "protocol-metadata.json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    files = sorted(glob.glob(DATA_GLOB))
    if not files:
        sys.exit(f"no service models found under {DATA_GLOB}; install awscli v2")

    services: dict[str, dict[str, str]] = {}
    conflicts: list[str] = []

    for path in files:
        try:
            with open(path, encoding="utf-8") as fh:
                metadata = json.load(fh).get("metadata", {})
        except Exception:  # noqa: BLE001 - a single unreadable model must not abort
            continue

        service_id = metadata.get("serviceId")
        target_prefix = metadata.get("targetPrefix")
        if not service_id or not target_prefix:
            continue

        existing = services.get(service_id, {}).get("targetPrefix")
        if existing is not None and existing != target_prefix:
            # Multiple API versions on disk disagreeing; the newest path sorts last, so
            # report and keep the later one.
            conflicts.append(f"{service_id}: {existing} -> {target_prefix}")
        services[service_id] = {"targetPrefix": target_prefix}

    payload = {
        "_comment": (
            "Generated by scripts/extract-protocol-metadata.py from botocore's "
            "service-2.json metadata. Do not hand-edit. targetPrefix is the X-Amz-Target "
            "prefix for awsJson protocols; the Smithy models omit it, and while the "
            "service shape name matches for most services it does NOT for all "
            "(cloudtrail, codeconnections, codestar-connections use a fully-qualified "
            "prefix), so it cannot be derived."
        ),
        "services": dict(sorted(services.items())),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(f"services with targetPrefix  {len(services)}", file=sys.stderr)
    if conflicts:
        print(f"version conflicts resolved  {len(conflicts)}", file=sys.stderr)
        for c in conflicts[:5]:
            print(f"    {c}", file=sys.stderr)
    print(
        f"wrote                       {args.output} ({os.path.getsize(args.output)} bytes)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
