#!/usr/bin/env python3
"""Vendor botocore's hand-seeded `_xform_cache`.

`xform_name` is two regex passes, but botocore pre-seeds its cache with entries the
regexes cannot produce -- `DescribeCachediSCSIVolumes` -> `describe-cached-iscsi-volumes`
(the regexes give `describe-cachedi-scsi-volumes`), plus the WhatsApp, PartiQL and HITs
families. Without these the affected operations are unreachable by the name the CLI
actually accepts.

Only the `-` (CLI) separator entries are vendored; the `_` entries are botocore's Python
attribute names and have no CLI meaning.

Usage:  scripts/extract-xform-cache.py [--output PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REFERENCE_SITE_PACKAGES = (
    "/opt/homebrew/Cellar/awscli/2.36.22/libexec/lib/python3.14/site-packages"
)
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "data" / "xform-cache.json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not os.path.isdir(REFERENCE_SITE_PACKAGES):
        sys.exit(f"reference install not found at {REFERENCE_SITE_PACKAGES}")
    sys.path.insert(0, REFERENCE_SITE_PACKAGES)

    from awscli.botocore import _xform_cache  # noqa: E402

    # Keep only the CLI separator, and only entries the regexes would get wrong -- an
    # entry that matches the computed value is redundant and just bloats the table.
    from awscli.botocore import _first_cap_regex, _end_cap_regex, _special_case_transform

    def computed(name: str, sep: str = "-") -> str:
        if sep in name:
            return name
        match = _special_case_transform.search(name)
        if match is not None:
            matched = match.group()
            name = f"{name[: -len(matched)]}{sep}{matched.lower()}"
        s1 = _first_cap_regex.sub(r"\1" + sep + r"\2", name)
        return _end_cap_regex.sub(r"\1" + sep + r"\2", s1).lower()

    overrides = {}
    redundant = 0
    for (name, sep), value in _xform_cache.items():
        if sep != "-":
            continue
        if computed(name) == value:
            redundant += 1
            continue
        overrides[name] = value

    payload = {
        "_comment": (
            "Generated by scripts/extract-xform-cache.py from botocore's seeded "
            "_xform_cache. Do not hand-edit. These operation names cannot be produced by "
            "xform_name's two regex passes, so the table is consulted first."
        ),
        "overrides": dict(sorted(overrides.items())),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(f"overrides  {len(overrides)}", file=sys.stderr)
    print(f"redundant  {redundant} (regex already agrees)", file=sys.stderr)
    print(f"wrote      {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
