#!/usr/bin/env python3
"""Extract botocore paginator metadata into a JSON overlay keyed by CLI names.

Why this exists
---------------
The Rust port derives its command surface from Smithy models, but botocore's
``paginators-1.json`` and Smithy's ``smithy.api#paginated`` trait disagree about
which operations paginate. The botocore data is ground truth -- it is what the
reference CLI uses to decide which operations get ``--max-items`` /
``--page-size`` / ``--starting-token`` -- so it is vendored here as an overlay.

Keying is by CLI-facing names so the Rust side can join trivially:

* service key: the ``aws <command>`` name (``s3api``, ``logs``, ``deploy``),
  read empirically from the clidriver command table exactly as
  ``extract-service-names.py`` does -- NOT the botocore data-directory name.
* operation key: ``xform_name(OperationName, '-')`` (``DescribeInstances`` ->
  ``describe-instances``).

Each paginator config object is transcribed verbatim from ``paginators-1.json``;
only the outer keys change. Entries are NOT cross-validated against the service
model. Services without a paginator file are omitted entirely.

Usage:  scripts/extract-paginators.py [--output PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REFERENCE_SITE_PACKAGES = (
    "/opt/homebrew/Cellar/awscli/2.36.22/libexec/lib/python3.14/site-packages"
)
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "data" / "paginators.json"


def load_reference():
    """Import awscli from the reference install, isolated from local AWS config."""
    if not os.path.isdir(REFERENCE_SITE_PACKAGES):
        sys.exit(
            f"reference install not found at {REFERENCE_SITE_PACKAGES}\n"
            "install awscli v2, or edit REFERENCE_SITE_PACKAGES."
        )
    sys.path.insert(0, REFERENCE_SITE_PACKAGES)

    # Keep local profiles, plugins and env from perturbing the surface.
    os.environ["AWS_CONFIG_FILE"] = os.devnull
    os.environ["AWS_SHARED_CREDENTIALS_FILE"] = os.devnull
    os.environ.pop("AWS_PROFILE", None)
    os.environ.pop("AWS_DEFAULT_PROFILE", None)

    from awscli.clidriver import create_clidriver  # noqa: E402

    return create_clidriver()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    driver = load_reference()

    # Importable only after load_reference() puts the reference install on sys.path.
    from awscli.botocore import xform_name  # noqa: E402

    # awscli v2 vendors botocore under `awscli.botocore` AND aliases it to
    # top-level `botocore` via an import hook, producing two DISTINCT module
    # instances of the same file. The loader raises exception classes from the
    # `botocore.exceptions` instance, so we must import from there --
    # `awscli.botocore.exceptions.DataNotFoundError` would not catch them.
    # Services with no paginators-1 file raise UnknownServiceError (a
    # DataNotFoundError subclass) because the loader validates the name against
    # the set of services that have that file type.
    from botocore.exceptions import DataNotFoundError  # noqa: E402

    session = driver.session
    loader = session.get_component("data_loader")

    command_table = driver._get_command_table()

    services: dict[str, dict[str, dict]] = {}
    total_entries = 0
    with_limit_key = 0

    for cli_name, command in sorted(command_table.items()):
        # ServiceCommand keeps the botocore directory name in the private
        # `_service_name` while the command-table key is the (possibly renamed)
        # CLI name (`s3` -> `s3api`, `codedeploy` -> `deploy`). Custom top-level
        # commands (`configure`, `history`, the high-level `s3`, ...) have no
        # botocore model and are skipped.
        botocore_name = getattr(command, "_service_name", None)
        if not botocore_name:
            continue

        try:
            paginators = loader.load_service_model(botocore_name, "paginators-1")
        except DataNotFoundError:
            # No paginator file for this service: normal, omit it entirely.
            continue

        pagination = paginators.get("pagination", {})
        if not pagination:
            continue

        ops: dict[str, dict] = {}
        for op_name, config in pagination.items():
            # Transcribe verbatim; only the key changes (PascalCase -> kebab-case).
            # Deliberately NOT cross-validated against service-2.
            ops[xform_name(op_name, "-")] = config
            total_entries += 1
            if "limit_key" in config:
                with_limit_key += 1

        services[cli_name] = ops

    payload = {
        "_comment": (
            "Generated by scripts/extract-paginators.py. botocore paginator "
            "configs keyed by CLI service and operation name. Do not hand-edit."
        ),
        "awscli_version": driver.session.user_agent_version,
        "services": services,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(f"services with paginators  {len(services)}", file=sys.stderr)
    print(f"paginator entries         {total_entries}", file=sys.stderr)
    print(f"  with limit_key          {with_limit_key}", file=sys.stderr)
    print(f"  without limit_key       {total_entries - with_limit_key}", file=sys.stderr)
    print(f"wrote                     {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
