#!/usr/bin/env python3
"""Vendor the AWS partitions table used by the endpoint rules `aws.partition` function.

`aws.partition(region)` returns a record of partition outputs (dnsSuffix,
implicitGlobalRegion, supportsFIPS, ...) that endpoint rulesets interpolate into URLs.
The table lives in botocore's `partitions.json`; the Smithy models reference it but do
not embed it.

Resolution order (matches the endpoint-rules spec): exact match in a partition's region
list, then that partition's `regionRegex`, then fall back to the `aws` partition. Region
entries carry only a human description -- there are no per-region output overrides -- so
only `outputs`, `regionRegex` and the region names are vendored.

Also vendors `partition_endpoints` from the LEGACY `endpoints.json`. When no region is
configured, botocore substitutes a service's `partitionEndpoint` as the region and only
raises NoRegionError if the service has none (`botocore/regions.py:274-281`). That is why
`aws sts get-caller-identity` works with no region configured -- it resolves to the
`aws-global` pseudo-region -- while `aws ec2 describe-regions` does not. The rulesets
themselves do NOT encode this, so it has to come from here.

Usage:  scripts/extract-partitions.py [--output PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REFERENCE_SITE_PACKAGES = (
    "/opt/homebrew/Cellar/awscli/2.36.22/libexec/lib/python3.14/site-packages"
)
SOURCE = Path(REFERENCE_SITE_PACKAGES) / "awscli/botocore/data/partitions.json"
ENDPOINTS_SOURCE = Path(REFERENCE_SITE_PACKAGES) / "awscli/botocore/data/endpoints.json"
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "data" / "partitions.json"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not SOURCE.exists():
        sys.exit(f"partitions.json not found at {SOURCE}; install awscli v2")

    with open(SOURCE, encoding="utf-8") as fh:
        raw = json.load(fh)

    partitions = []
    for part in raw["partitions"]:
        partitions.append(
            {
                "id": part["id"],
                "regionRegex": part["regionRegex"],
                # Sorted for determinism; the descriptions are dropped as unused.
                "regions": sorted(part["regions"]),
                "outputs": part["outputs"],
            }
        )

    # partition id -> service -> partitionEndpoint, from the legacy endpoints.json.
    # Kept per-partition because the pseudo-region genuinely differs (`aws-global` vs
    # `aws-cn-global`); flattening would send China-partition users to the wrong host.
    # Services are keyed by botocore's endpoints.json name, i.e. the endpoint prefix.
    if not ENDPOINTS_SOURCE.exists():
        sys.exit(f"endpoints.json not found at {ENDPOINTS_SOURCE}")

    with open(ENDPOINTS_SOURCE, encoding="utf-8") as fh:
        endpoints = json.load(fh)

    partition_endpoints: dict[str, dict[str, str]] = {}
    for part in endpoints.get("partitions", []):
        found = {
            service: data["partitionEndpoint"]
            for service, data in part.get("services", {}).items()
            if "partitionEndpoint" in data
        }
        if found:
            partition_endpoints[part["partition"]] = dict(sorted(found.items()))

    payload = {
        "_comment": (
            "Generated by scripts/extract-partitions.py from botocore's partitions.json "
            "and endpoints.json. Do not hand-edit. `partitions` feeds the endpoint-rules "
            "`aws.partition` function: match a region against `regions` exactly, then "
            "`regionRegex`, else fall back to the partition with id `aws`. "
            "`partition_endpoints` maps partition -> service -> the pseudo-region "
            "botocore substitutes when no region is configured (regions.py:274-281); a "
            "service absent from it raises NoRegionError instead. With no region there "
            "is no partition either, so lookups use the `aws` partition, which is what "
            "botocore's partition iteration order arrives at."
        ),
        "source_version": raw.get("version"),
        "partitions": partitions,
        "partition_endpoints": dict(sorted(partition_endpoints.items())),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")

    total_regions = sum(len(p["regions"]) for p in partitions)
    print(f"partitions  {len(partitions)}", file=sys.stderr)
    print(f"regions     {total_regions}", file=sys.stderr)
    print(
        f"global svcs {sum(len(v) for v in partition_endpoints.values())} "
        f"across {len(partition_endpoints)} partitions",
        file=sys.stderr,
    )
    print(f"wrote       {args.output} ({os.path.getsize(args.output)} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
