//! Runtime access to the customization tables the conformance harness already uses.
//!
//! [`crate::customizations::Customizations`] is loaded from a path by the harness. The
//! binary needs the same two tables without a file to point at, so they are embedded here
//! and shared — one source of truth, `data/customizations.json`, regenerated by
//! `scripts/extract-customizations.py`.
//!
//! Two behaviours depend on this:
//!
//! - **Removals**: v2 deletes commands from sixteen services' command tables. Accepting a
//!   command the reference does not know makes us a superset, which is its own kind of
//!   wrong — the surface builder already skipped these, so only the binary was affected.
//! - **Argument renames**: 87 `service.operation.argument` rules. Without them we expose
//!   the derived name and reject the one the reference accepts.

use crate::customizations::Customizations;
use std::sync::LazyLock;

static EMBEDDED: LazyLock<Customizations> = LazyLock::new(|| {
    let text = include_str!("../../../data/customizations.json");
    serde_json::from_str(text).expect("embedded data/customizations.json is malformed")
});

pub fn get() -> &'static Customizations {
    &EMBEDDED
}

static EMBEDDED_SURFACE: LazyLock<crate::custom_surface::CustomSurface> = LazyLock::new(|| {
    let text = include_str!("../../../data/custom-surface.json");
    serde_json::from_str(text).expect("embedded data/custom-surface.json is malformed")
});

/// The per-service surface customizations, embedded for the binary.
pub fn custom_surface() -> &'static crate::custom_surface::CustomSurface {
    &EMBEDDED_SURFACE
}

/// Whether this command is hidden.
pub fn is_removed(service: &str, operation: &str) -> bool {
    EMBEDDED.is_removed(service, operation)
}

/// The renamed form of an argument, if a rule applies.
pub fn rename_argument(service: &str, operation: &str, argument: &str) -> String {
    let original = format!("--{argument}");
    let mut set = std::collections::BTreeSet::new();
    set.insert(original.clone());
    EMBEDDED.apply_argument_rules(service, operation, &mut set);
    // A rename replaces the flag; a hidden alias adds one alongside it. Either way the
    // renamed form is the entry that is not the original.
    set.iter()
        .find(|f| **f != original)
        .cloned()
        .unwrap_or(original)
        .trim_start_matches("--")
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn knows_the_removed_commands() {
        assert!(is_removed("ses", "delete-verified-email-address"));
        assert!(is_removed("ses", "verify-email-address"));
        assert!(is_removed("ec2", "import-instance"));
        assert!(!is_removed("ses", "send-email"));
        assert!(!is_removed("ec2", "describe-instances"));
        assert!(!is_removed("s3api", "get-object"));
    }

    /// The reference removes these because it cannot read an event stream. We can, so
    /// they stay visible — while the duplex ones, which we genuinely cannot do, do not.
    #[test]
    fn keeps_the_event_stream_operations_the_reference_drops() {
        assert!(!is_removed("kinesis", "subscribe-to-shard"));
        assert!(!is_removed("lambda", "invoke-with-response-stream"));
        assert!(!is_removed("logs", "get-log-object"));
        assert!(!is_removed("bedrock-runtime", "converse-stream"));
        assert!(!is_removed("bedrock-runtime", "invoke-model-with-response-stream"));

        // Duplex operations too, now that request events can be signed and sent.
        assert!(!is_removed("bedrock-runtime", "invoke-model-with-bidirectional-stream"));
        assert!(!is_removed("polly", "start-speech-synthesis-stream"));
        assert!(!is_removed("qbusiness", "chat"));
        assert!(!is_removed("lexv2-runtime", "start-conversation"));

        // Every override has to name a removal the reference actually makes, or it is
        // silently doing nothing — a typo would look exactly like success.
        for (service, operation) in crate::customizations::EVENT_STREAM_OPERATIONS {
            assert!(
                EMBEDDED
                    .removed_operations
                    .get(*service)
                    .is_some_and(|ops| ops.iter().any(|o| o == operation)),
                "{service} {operation} is not in the reference's removal list"
            );
        }
    }

    #[test]
    fn covers_every_service_the_reference_touches() {
        assert_eq!(get().removed_operations.len(), 16, "removal table changed size");
        assert!(get().argument_renames.len() >= 80, "rename table looks truncated");
    }

    #[test]
    fn renames_arguments() {
        assert_eq!(rename_argument("sns", "subscribe", "endpoint"), "notification-endpoint");
        assert_eq!(rename_argument("swf", "register-activity-type", "version"), "activity-version");
        // `emr.*.job-flow-ids` applies to every emr operation.
        assert_eq!(rename_argument("emr", "add-tags", "job-flow-ids"), "cluster-ids");
        assert_eq!(rename_argument("emr", "anything-else", "job-flow-id"), "cluster-id");
        // The same argument name is untouched elsewhere.
        assert_eq!(rename_argument("sns", "publish", "endpoint"), "endpoint");
        assert_eq!(rename_argument("ec2", "describe-instances", "filters"), "filters");
    }

    #[test]
    fn scoped_renames_do_not_leak() {
        assert_eq!(
            rename_argument("route53", "get-traffic-policy", "version"),
            "traffic-policy-version"
        );
        assert_eq!(rename_argument("route53", "create-hosted-zone", "version"), "version");
    }

    /// The embedded copy and the file the harness loads must be the same table, or the
    /// binary and the conformance report would disagree about the surface.
    #[test]
    fn embedded_table_matches_the_file_on_disk() {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../data/customizations.json");
        let from_disk = Customizations::load(&path).expect("customizations.json should load");
        assert_eq!(from_disk.removed_operations, get().removed_operations);
        assert_eq!(from_disk.argument_renames, get().argument_renames);
    }
}
